#import <Foundation/Foundation.h>
#import <EndpointSecurity/EndpointSecurity.h>
#import <bsm/libbsm.h>
#include <sys/param.h>
#include <sys/mount.h>
#import "es_wrapper.h"

// Auto-generated by cgo for //export directives
#include "_cgo_export.h"

es_new_client_result_t create_es_client(es_client_t **client) {
    return es_new_client(client, ^(es_client_t *c, const es_message_t *msg) {
        // Call the exported Go function, casting away const
        esEventCallback_cgo(c, (es_message_t *)msg);
    });
}

pid_t get_pid(const es_message_t *msg) {
    if (!msg || !msg->process) return -1;
    return audit_token_to_pid(msg->process->audit_token);
}

pid_t get_ppid(const es_message_t *msg) {
    if (!msg || !msg->process) return -1;
    return msg->process->ppid;
}

uint32_t get_uid(const es_message_t *msg) {
    if (!msg || !msg->process) return -1;
    return audit_token_to_ruid(msg->process->audit_token);
}

const char* get_executable_path(const es_message_t *msg, int *out_len) {
    if (!msg || !msg->process || !msg->process->executable) {
        *out_len = 0;
        return "";
    }
	*out_len = (int)msg->process->executable->path.length;
    return msg->process->executable->path.data;
}

const char* get_mount_path(const es_message_t *msg, int *out_len) {
    if (!msg || msg->event_type != ES_EVENT_TYPE_NOTIFY_MOUNT || !msg->event.mount.statfs) {
        *out_len = 0;
        return "";
    }
    // Apple statfs definition uses char f_mntonname[MAXPATHLEN]
    const char *path = msg->event.mount.statfs->f_mntonname;
    *out_len = (int)strnlen(path, MAXPATHLEN);
    return path;
}
