#import <Foundation/Foundation.h>
#import <EndpointSecurity/EndpointSecurity.h>
#import <bsm/libbsm.h>
#include <sys/param.h>
#include <sys/mount.h>
#import "es_wrapper.h"

// Auto-generated by cgo for //export directives
#include "_cgo_export.h"

es_new_client_result_t create_es_client(es_client_t **client) {
    return es_new_client(client, ^(es_client_t *c, const es_message_t *msg) {
        // Call the exported Go function, casting away const
        esEventCallback_cgo(c, (es_message_t *)msg);
    });
}

pid_t get_pid(const es_message_t *msg) {
    if (!msg || !msg->process) return -1;
    return audit_token_to_pid(msg->process->audit_token);
}

pid_t get_ppid(const es_message_t *msg) {
    if (!msg || !msg->process) return -1;
    return msg->process->ppid;
}

uint32_t get_uid(const es_message_t *msg) {
    if (!msg || !msg->process) return -1;
    return audit_token_to_ruid(msg->process->audit_token);
}

const char* get_executable_path(const es_message_t *msg, int *out_len) {
    if (!msg || !msg->process || !msg->process->executable) {
        *out_len = 0;
        return "";
    }
	*out_len = (int)msg->process->executable->path.length;
    return msg->process->executable->path.data;
}

const char* get_mount_path(const es_message_t *msg, int *out_len) {
    if (!msg || msg->event_type != ES_EVENT_TYPE_NOTIFY_MOUNT || !msg->event.mount.statfs) {
        *out_len = 0;
        return "";
    }
    // Apple statfs definition uses char f_mntonname[MAXPATHLEN]
    const char *path = msg->event.mount.statfs->f_mntonname;
    *out_len = (int)strnlen(path, MAXPATHLEN);
    return path;
}

const char* get_target_path(const es_message_t *msg, int *out_len) {
    if (!msg || msg->event_type != ES_EVENT_TYPE_NOTIFY_WRITE || !msg->event.write.target) {
        *out_len = 0;
        return "";
    }
    *out_len = (int)msg->event.write.target->path.length;
    return msg->event.write.target->path.data;
}

const char* get_open_target_path(const es_message_t *msg, int *out_len) {
    if (!msg || msg->event_type != ES_EVENT_TYPE_AUTH_OPEN || !msg->event.open.file) {
        *out_len = 0;
        return "";
    }
    *out_len = (int)msg->event.open.file->path.length;
    return msg->event.open.file->path.data;
}

bool open_requests_write(const es_message_t *msg) {
    if (!msg || msg->event_type != ES_EVENT_TYPE_AUTH_OPEN) return false;
    return (msg->event.open.fflag & (FWRITE | O_APPEND | O_TRUNC)) != 0;
}

uint32_t auth_open_event_code(void) {
    return (uint32_t)ES_EVENT_TYPE_AUTH_OPEN;
}

void retain_message_safe(const es_message_t *msg) {
    if (!msg) return;

    // es_retain_message is available on macOS 11.0+
    if (@available(macOS 11.0, *)) {
        es_retain_message(msg);
    }
}

void respond_auth_and_release(es_client_t *client, const es_message_t *msg, bool allow, bool cache) {
    if (!client || !msg) return;

    es_auth_result_t result = allow ? ES_AUTH_RESULT_ALLOW : ES_AUTH_RESULT_DENY;
    es_respond_auth_result(client, msg, result, cache);

    // Release the message since we retained it in Go before going async
    // es_release_message is available on macOS 11.0+
    if (@available(macOS 11.0, *)) {
        es_release_message(msg);
    }
}
