# Build Stage
FROM golang:1.25.7-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the server
RUN CGO_ENABLED=0 GOOS=linux go build -o aftersec-server ./cmd/aftersec-server

# Final Stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/aftersec-server .
COPY --from=builder /app/migrations ./migrations
COPY --from=builder /app/certs ./certs

EXPOSE 8080 9090

# Standard execution
CMD ["./aftersec-server"]
