package plugins

import (
	"crypto/sha256"
	"debug/elf"
	"debug/macho"
	"debug/pe"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"
)

const yaraRuleTemplate = `import "hash"

rule AutoImmunity_{{ .Hash }} {
    meta:
        description = "Auto-generated by AfterSec Immunity Engine"
        reason = "{{ .Reason }}"
        date = "{{ .Date }}"
        author = "AfterSec EDR"
    strings:
{{- range $i, $str := .Strings }}
        $s{{ $i }} = "{{ $str }}"
{{- end }}
    condition:
        all of them and hash.sha256(0, filesize) == "{{ .Hash }}"
}
`

type YaraRuleData struct {
	Hash    string
	Reason  string
	Date    string
	Strings []string
}

// GenerateImmunitySignature automatically extracts structural capabilities from a convicted payload
// and deploys a local YARA rule to uniquely block future executions of the exact file properties.
func GenerateImmunitySignature(targetPath string, reason string) error {
	// 1. Calculate SHA256 Hash
	hashStr, err := calculateHash(targetPath)
	if err != nil {
		return fmt.Errorf("failed to hash payload %s: %w", targetPath, err)
	}

	// 2. Extract Structural Indicators (Mach-O, ELF, PE)
	indicators := extractCapabilities(targetPath)
	if len(indicators) == 0 {
		return fmt.Errorf("no structural indicators extracted from %s", targetPath)
	}

	// Cap to max 5 indicators to prevent oversized rules, prioritizing the longest/most unique
	if len(indicators) > 5 {
		indicators = indicators[:5]
	}

	// 3. Compile YARA Rule
	data := YaraRuleData{
		Hash:    hashStr,
		Reason:  reason,
		Date:    time.Now().Format(time.RFC3339),
		Strings: indicators,
	}

	tmpl, err := template.New("yara").Parse(yaraRuleTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse YARA template: %w", err)
	}

	// 4. Save to `~/.aftersec/rules`
	rulesDir := getRulesDir()
	if err := os.MkdirAll(rulesDir, 0755); err != nil {
		return fmt.Errorf("failed to create YARA rules directory: %w", err)
	}

	rulePath := filepath.Join(rulesDir, fmt.Sprintf("immunity_%s.yar", hashStr))
	f, err := os.Create(rulePath)
	if err != nil {
		return fmt.Errorf("failed to write immunity rule: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("failed to render immunity rule: %w", err)
	}

	log.Printf("🛡️ [IMMUNITY ENGINE] successfully deployed localized YARA signature: %s", rulePath)
	return nil
}

func calculateHash(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}

func extractCapabilities(path string) []string {
	var indicators []string

	if fInfo, err := macho.OpenFat(path); err == nil {
		defer fInfo.Close()
		for _, arch := range fInfo.Arches {
			indicators = append(indicators, extractMachO(arch.File)...)
		}
		if len(indicators) > 0 {
			return filterAndClean(indicators)
		}
	}

	if mInfo, err := macho.Open(path); err == nil {
		defer mInfo.Close()
		indicators = append(indicators, extractMachO(mInfo)...)
		if len(indicators) > 0 {
			return filterAndClean(indicators)
		}
	}

	if eInfo, err := elf.Open(path); err == nil {
		defer eInfo.Close()
		indicators = append(indicators, extractELF(eInfo)...)
		if len(indicators) > 0 {
			return filterAndClean(indicators)
		}
	}

	if pInfo, err := pe.Open(path); err == nil {
		defer pInfo.Close()
		indicators = append(indicators, extractPE(pInfo)...)
		if len(indicators) > 0 {
			return filterAndClean(indicators)
		}
	}

	return indicators
}

func extractMachO(m *macho.File) []string {
	var results []string
	
	// Extract Imported Libraries
	libs, err := m.ImportedLibraries()
	if err == nil {
		results = append(results, libs...)
	}

	// Extract Imported Symbols
	syms, err := m.ImportedSymbols()
	if err == nil {
		results = append(results, syms...)
	}

	return results
}

func extractELF(e *elf.File) []string {
	var results []string

	// Extract Imported Libraries
	libs, err := e.ImportedLibraries()
	if err == nil {
		results = append(results, libs...)
	}

	// Extract Imported Symbols
	syms, err := e.ImportedSymbols()
	if err == nil {
		for _, s := range syms {
			results = append(results, s.Name)
		}
	}

	return results
}

func extractPE(p *pe.File) []string {
	var results []string

	// Extract Imported Libraries & Symbols
	syms, err := p.ImportedSymbols()
	if err == nil {
		for _, s := range syms {
			// e.g., KERNEL32.dll:CreateProcessA
			results = append(results, s) // debug/pe just gives the func name
		}
	}

	return results
}

func filterAndClean(raw []string) []string {
	var clean []string
	seen := make(map[string]bool)

	// Exclude overly common generic runtime dependencies that cause FPs
	excludes := []string{"libSystem.B.dylib", "libc.so.6", "KERNEL32.dll", "crt1.o", "_exit", "malloc", "free", "printf"}

	for _, s := range raw {
		s = strings.TrimSpace(s)
		
		// Ensure string represents a substantial capability (at least 6 chars)
		if len(s) < 6 || len(s) > 100 {
			continue
		}

		// Escape backslashes and quotes for safe YARA rendering
		s = strings.ReplaceAll(s, "\\", "\\\\")
		s = strings.ReplaceAll(s, "\"", "\\\"")

		excluded := false
		for _, ex := range excludes {
			if strings.EqualFold(s, ex) {
				excluded = true
				break
			}
		}

		if !excluded && !seen[s] && isASCII(s) {
			seen[s] = true
			clean = append(clean, s)
		}
	}
	return clean
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] > 127 || s[i] < 32 {
			return false
		}
	}
	return true
}
