// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/aftersec.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HardwareId    string                 `protobuf:"bytes,1,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *EnrollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HardwareId    string                 `protobuf:"bytes,2,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HeartbeatRequest) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyUpdated bool                   `protobuf:"varint,1,opt,name=policy_updated,json=policyUpdated,proto3" json:"policy_updated,omitempty"`
	NewPolicyHash string                 `protobuf:"bytes,2,opt,name=new_policy_hash,json=newPolicyHash,proto3" json:"new_policy_hash,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "NONE", "RESTART", "UPDATE", "QUARANTINE", "LOCK_SCREEN", "WIPE_DATA"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetPolicyUpdated() bool {
	if x != nil {
		return x.PolicyUpdated
	}
	return false
}

func (x *HeartbeatResponse) GetNewPolicyHash() string {
	if x != nil {
		return x.NewPolicyHash
	}
	return ""
}

func (x *HeartbeatResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ClientEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HardwareId    string                 `protobuf:"bytes,2,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "SYSCALL", "FILE_MOD", "NETWORK_CONN"
	ProcessName   string                 `protobuf:"bytes,5,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessId     int32                  `protobuf:"varint,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Payload       string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // JSON encoded details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_api_proto_aftersec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{4}
}

func (x *ClientEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ClientEvent) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *ClientEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ClientEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *ClientEvent) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ClientEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type StreamAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventsProcessed int32                  `protobuf:"varint,1,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_api_proto_aftersec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{5}
}

func (x *StreamAck) GetEventsProcessed() int32 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *StreamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HardwareId    string                 `protobuf:"bytes,2,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "ACK", "SUCCESS", "FAILED"
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_api_proto_aftersec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CommandResult) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "EXEC", "REMEDIATE", "LOCK_SCREEN", "WIPE_DATA", "QUARANTINE"
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_api_proto_aftersec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{7}
}

func (x *ServerCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ServerCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_api_proto_aftersec_proto protoreflect.FileDescriptor

const file_api_proto_aftersec_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/aftersec.proto\x12\faftersec.api\"\x90\x01\n" +
	"\rEnrollRequest\x12\x1f\n" +
	"\vhardware_id\x18\x01 \x01(\tR\n" +
	"hardwareId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"\x84\x01\n" +
	"\x0eEnrollResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x86\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vhardware_id\x18\x02 \x01(\tR\n" +
	"hardwareId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"z\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0epolicy_updated\x18\x01 \x01(\bR\rpolicyUpdated\x12&\n" +
	"\x0fnew_policy_hash\x18\x02 \x01(\tR\rnewPolicyHash\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xe4\x01\n" +
	"\vClientEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vhardware_id\x18\x02 \x01(\tR\n" +
	"hardwareId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fprocess_name\x18\x05 \x01(\tR\vprocessName\x12\x1d\n" +
	"\n" +
	"process_id\x18\x06 \x01(\x05R\tprocessId\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\"P\n" +
	"\tStreamAck\x12)\n" +
	"\x10events_processed\x18\x01 \x01(\x05R\x0feventsProcessed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\rCommandResult\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vhardware_id\x18\x02 \x01(\tR\n" +
	"hardwareId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\"`\n" +
	"\rServerCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload2\xc2\x02\n" +
	"\x11EnterpriseService\x12C\n" +
	"\x06Enroll\x12\x1b.aftersec.api.EnrollRequest\x1a\x1c.aftersec.api.EnrollResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.aftersec.api.HeartbeatRequest\x1a\x1f.aftersec.api.HeartbeatResponse\x12D\n" +
	"\fStreamEvents\x12\x19.aftersec.api.ClientEvent\x1a\x17.aftersec.api.StreamAck(\x01\x12T\n" +
	"\x14ConnectCommandStream\x12\x1b.aftersec.api.CommandResult\x1a\x1b.aftersec.api.ServerCommand(\x010\x01B\x1fZ\x1daftersec/pkg/api/grpc;grpcapib\x06proto3"

var (
	file_api_proto_aftersec_proto_rawDescOnce sync.Once
	file_api_proto_aftersec_proto_rawDescData []byte
)

func file_api_proto_aftersec_proto_rawDescGZIP() []byte {
	file_api_proto_aftersec_proto_rawDescOnce.Do(func() {
		file_api_proto_aftersec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_aftersec_proto_rawDesc), len(file_api_proto_aftersec_proto_rawDesc)))
	})
	return file_api_proto_aftersec_proto_rawDescData
}

var file_api_proto_aftersec_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_aftersec_proto_goTypes = []any{
	(*EnrollRequest)(nil),     // 0: aftersec.api.EnrollRequest
	(*EnrollResponse)(nil),    // 1: aftersec.api.EnrollResponse
	(*HeartbeatRequest)(nil),  // 2: aftersec.api.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: aftersec.api.HeartbeatResponse
	(*ClientEvent)(nil),       // 4: aftersec.api.ClientEvent
	(*StreamAck)(nil),         // 5: aftersec.api.StreamAck
	(*CommandResult)(nil),     // 6: aftersec.api.CommandResult
	(*ServerCommand)(nil),     // 7: aftersec.api.ServerCommand
}
var file_api_proto_aftersec_proto_depIdxs = []int32{
	0, // 0: aftersec.api.EnterpriseService.Enroll:input_type -> aftersec.api.EnrollRequest
	2, // 1: aftersec.api.EnterpriseService.Heartbeat:input_type -> aftersec.api.HeartbeatRequest
	4, // 2: aftersec.api.EnterpriseService.StreamEvents:input_type -> aftersec.api.ClientEvent
	6, // 3: aftersec.api.EnterpriseService.ConnectCommandStream:input_type -> aftersec.api.CommandResult
	1, // 4: aftersec.api.EnterpriseService.Enroll:output_type -> aftersec.api.EnrollResponse
	3, // 5: aftersec.api.EnterpriseService.Heartbeat:output_type -> aftersec.api.HeartbeatResponse
	5, // 6: aftersec.api.EnterpriseService.StreamEvents:output_type -> aftersec.api.StreamAck
	7, // 7: aftersec.api.EnterpriseService.ConnectCommandStream:output_type -> aftersec.api.ServerCommand
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_aftersec_proto_init() }
func file_api_proto_aftersec_proto_init() {
	if File_api_proto_aftersec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_aftersec_proto_rawDesc), len(file_api_proto_aftersec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_aftersec_proto_goTypes,
		DependencyIndexes: file_api_proto_aftersec_proto_depIdxs,
		MessageInfos:      file_api_proto_aftersec_proto_msgTypes,
	}.Build()
	File_api_proto_aftersec_proto = out.File
	file_api_proto_aftersec_proto_goTypes = nil
	file_api_proto_aftersec_proto_depIdxs = nil
}
