// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: api/proto/aftersec.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HardwareId       string                 `protobuf:"bytes,1,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	OsVersion        string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	AgentVersion     string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,5,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	EnrollmentCode   string                 `protobuf:"bytes,6,opt,name=enrollment_code,json=enrollmentCode,proto3" json:"enrollment_code,omitempty"`
	Platform         string                 `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	AttestationNonce []byte                 `protobuf:"bytes,8,opt,name=attestation_nonce,json=attestationNonce,proto3" json:"attestation_nonce,omitempty"`
	AttestationQuote []byte                 `protobuf:"bytes,9,opt,name=attestation_quote,json=attestationQuote,proto3" json:"attestation_quote,omitempty"`
	PublicKey        []byte                 `protobuf:"bytes,10,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EnrollRequest) GetEnrollmentCode() string {
	if x != nil {
		return x.EnrollmentCode
	}
	return ""
}

func (x *EnrollRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *EnrollRequest) GetAttestationNonce() []byte {
	if x != nil {
		return x.AttestationNonce
	}
	return nil
}

func (x *EnrollRequest) GetAttestationQuote() []byte {
	if x != nil {
		return x.AttestationQuote
	}
	return nil
}

func (x *EnrollRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type EnrollResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TenantId             string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AccessToken          string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Success              bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ClientCertificate    []byte                 `protobuf:"bytes,5,opt,name=client_certificate,json=clientCertificate,proto3" json:"client_certificate,omitempty"`
	CertificateExpiresAt int64                  `protobuf:"varint,6,opt,name=certificate_expires_at,json=certificateExpiresAt,proto3" json:"certificate_expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *EnrollResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnrollResponse) GetClientCertificate() []byte {
	if x != nil {
		return x.ClientCertificate
	}
	return nil
}

func (x *EnrollResponse) GetCertificateExpiresAt() int64 {
	if x != nil {
		return x.CertificateExpiresAt
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HardwareId    string                 `protobuf:"bytes,2,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *HeartbeatRequest) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyUpdated bool                   `protobuf:"varint,1,opt,name=policy_updated,json=policyUpdated,proto3" json:"policy_updated,omitempty"`
	NewPolicyHash string                 `protobuf:"bytes,2,opt,name=new_policy_hash,json=newPolicyHash,proto3" json:"new_policy_hash,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "NONE", "RESTART", "UPDATE", "QUARANTINE", "LOCK_SCREEN", "WIPE_DATA", "ISOLATE_NETWORK", "FREEZE_PROCESS"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetPolicyUpdated() bool {
	if x != nil {
		return x.PolicyUpdated
	}
	return false
}

func (x *HeartbeatResponse) GetNewPolicyHash() string {
	if x != nil {
		return x.NewPolicyHash
	}
	return ""
}

func (x *HeartbeatResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ClientEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HardwareId      string                 `protobuf:"bytes,2,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	Timestamp       int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType       string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "SYSCALL", "FILE_MOD", "NETWORK_CONN", "PROCESS_EXEC", "PROCESS_EXIT", "INTENT_GRAPH_BLOCK", "AI_TRIAGE"
	ProcessName     string                 `protobuf:"bytes,5,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	ProcessId       int32                  `protobuf:"varint,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Payload         string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // JSON encoded details
	ParentProcessId int32                  `protobuf:"varint,8,opt,name=parent_process_id,json=parentProcessId,proto3" json:"parent_process_id,omitempty"`
	ThreatScore     int32                  `protobuf:"varint,9,opt,name=threat_score,json=threatScore,proto3" json:"threat_score,omitempty"`
	AiVerdict       string                 `protobuf:"bytes,10,opt,name=ai_verdict,json=aiVerdict,proto3" json:"ai_verdict,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_api_proto_aftersec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{4}
}

func (x *ClientEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ClientEvent) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *ClientEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ClientEvent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *ClientEvent) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *ClientEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ClientEvent) GetParentProcessId() int32 {
	if x != nil {
		return x.ParentProcessId
	}
	return 0
}

func (x *ClientEvent) GetThreatScore() int32 {
	if x != nil {
		return x.ThreatScore
	}
	return 0
}

func (x *ClientEvent) GetAiVerdict() string {
	if x != nil {
		return x.AiVerdict
	}
	return ""
}

type StreamAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventsProcessed int32                  `protobuf:"varint,1,opt,name=events_processed,json=eventsProcessed,proto3" json:"events_processed,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_api_proto_aftersec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{5}
}

func (x *StreamAck) GetEventsProcessed() int32 {
	if x != nil {
		return x.EventsProcessed
	}
	return 0
}

func (x *StreamAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	HardwareId    string                 `protobuf:"bytes,2,opt,name=hardware_id,json=hardwareId,proto3" json:"hardware_id,omitempty"`
	CommandId     string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "ACK", "SUCCESS", "FAILED"
	Output        string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_api_proto_aftersec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CommandResult) GetHardwareId() string {
	if x != nil {
		return x.HardwareId
	}
	return ""
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "EXEC", "REMEDIATE", "LOCK_SCREEN", "WIPE_DATA", "QUARANTINE", "ISOLATE_NETWORK", "FREEZE_PROCESS", "CREATE_SNAPSHOT"
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_api_proto_aftersec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{7}
}

func (x *ServerCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ServerCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ServerCommand) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ScanRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilePath       string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Recursive      bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	EnabledEngines []string               `protobuf:"bytes,3,rep,name=enabled_engines,json=enabledEngines,proto3" json:"enabled_engines,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{8}
}

func (x *ScanRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ScanRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *ScanRequest) GetEnabledEngines() []string {
	if x != nil {
		return x.EnabledEngines
	}
	return nil
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Infected      bool                   `protobuf:"varint,2,opt,name=infected,proto3" json:"infected,omitempty"`
	ThreatLevel   string                 `protobuf:"bytes,3,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"`
	Threats       []*Threat              `protobuf:"bytes,4,rep,name=threats,proto3" json:"threats,omitempty"`
	EnginesUsed   []string               `protobuf:"bytes,5,rep,name=engines_used,json=enginesUsed,proto3" json:"engines_used,omitempty"`
	ScanDuration  string                 `protobuf:"bytes,6,opt,name=scan_duration,json=scanDuration,proto3" json:"scan_duration,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{9}
}

func (x *ScanResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ScanResponse) GetInfected() bool {
	if x != nil {
		return x.Infected
	}
	return false
}

func (x *ScanResponse) GetThreatLevel() string {
	if x != nil {
		return x.ThreatLevel
	}
	return ""
}

func (x *ScanResponse) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *ScanResponse) GetEnginesUsed() []string {
	if x != nil {
		return x.EnginesUsed
	}
	return nil
}

func (x *ScanResponse) GetScanDuration() string {
	if x != nil {
		return x.ScanDuration
	}
	return ""
}

func (x *ScanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Threat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Threat) Reset() {
	*x = Threat{}
	mi := &file_api_proto_aftersec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Threat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Threat) ProtoMessage() {}

func (x *Threat) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Threat.ProtoReflect.Descriptor instead.
func (*Threat) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{10}
}

func (x *Threat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Threat) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Threat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Threat) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{11}
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalScans    int32                  `protobuf:"varint,1,opt,name=total_scans,json=totalScans,proto3" json:"total_scans,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Scans         []*HistoryEntry        `protobuf:"bytes,3,rep,name=scans,proto3" json:"scans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryResponse) GetTotalScans() int32 {
	if x != nil {
		return x.TotalScans
	}
	return 0
}

func (x *HistoryResponse) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *HistoryResponse) GetScans() []*HistoryEntry {
	if x != nil {
		return x.Scans
	}
	return nil
}

type HistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Infected      bool                   `protobuf:"varint,3,opt,name=infected,proto3" json:"infected,omitempty"`
	ThreatCount   int32                  `protobuf:"varint,4,opt,name=threat_count,json=threatCount,proto3" json:"threat_count,omitempty"`
	ThreatNames   []string               `protobuf:"bytes,5,rep,name=threat_names,json=threatNames,proto3" json:"threat_names,omitempty"`
	EnginesUsed   []string               `protobuf:"bytes,6,rep,name=engines_used,json=enginesUsed,proto3" json:"engines_used,omitempty"`
	ScanDuration  string                 `protobuf:"bytes,7,opt,name=scan_duration,json=scanDuration,proto3" json:"scan_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	mi := &file_api_proto_aftersec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HistoryEntry) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *HistoryEntry) GetInfected() bool {
	if x != nil {
		return x.Infected
	}
	return false
}

func (x *HistoryEntry) GetThreatCount() int32 {
	if x != nil {
		return x.ThreatCount
	}
	return 0
}

func (x *HistoryEntry) GetThreatNames() []string {
	if x != nil {
		return x.ThreatNames
	}
	return nil
}

func (x *HistoryEntry) GetEnginesUsed() []string {
	if x != nil {
		return x.EnginesUsed
	}
	return nil
}

func (x *HistoryEntry) GetScanDuration() string {
	if x != nil {
		return x.ScanDuration
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_aftersec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{14}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	Results       []*SearchResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_aftersec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{15}
}

func (x *SearchResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileHash      string                 `protobuf:"bytes,3,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	Infected      bool                   `protobuf:"varint,4,opt,name=infected,proto3" json:"infected,omitempty"`
	Threats       []*Threat              `protobuf:"bytes,5,rep,name=threats,proto3" json:"threats,omitempty"`
	EnginesUsed   []string               `protobuf:"bytes,6,rep,name=engines_used,json=enginesUsed,proto3" json:"engines_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_api_proto_aftersec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_aftersec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_api_proto_aftersec_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResult) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SearchResult) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SearchResult) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *SearchResult) GetInfected() bool {
	if x != nil {
		return x.Infected
	}
	return false
}

func (x *SearchResult) GetThreats() []*Threat {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *SearchResult) GetEnginesUsed() []string {
	if x != nil {
		return x.EnginesUsed
	}
	return nil
}

var File_api_proto_aftersec_proto protoreflect.FileDescriptor

const file_api_proto_aftersec_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/aftersec.proto\x12\faftersec.api\"\xf7\x02\n" +
	"\rEnrollRequest\x12\x1f\n" +
	"\vhardware_id\x18\x01 \x01(\tR\n" +
	"hardwareId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12'\n" +
	"\x0forganization_id\x18\x05 \x01(\tR\x0eorganizationId\x12'\n" +
	"\x0fenrollment_code\x18\x06 \x01(\tR\x0eenrollmentCode\x12\x1a\n" +
	"\bplatform\x18\a \x01(\tR\bplatform\x12+\n" +
	"\x11attestation_nonce\x18\b \x01(\fR\x10attestationNonce\x12+\n" +
	"\x11attestation_quote\x18\t \x01(\fR\x10attestationQuote\x12\x1d\n" +
	"\n" +
	"public_key\x18\n" +
	" \x01(\fR\tpublicKey\"\xe9\x01\n" +
	"\x0eEnrollResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12-\n" +
	"\x12client_certificate\x18\x05 \x01(\fR\x11clientCertificate\x124\n" +
	"\x16certificate_expires_at\x18\x06 \x01(\x03R\x14certificateExpiresAt\"\x86\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vhardware_id\x18\x02 \x01(\tR\n" +
	"hardwareId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"z\n" +
	"\x11HeartbeatResponse\x12%\n" +
	"\x0epolicy_updated\x18\x01 \x01(\bR\rpolicyUpdated\x12&\n" +
	"\x0fnew_policy_hash\x18\x02 \x01(\tR\rnewPolicyHash\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xd2\x02\n" +
	"\vClientEvent\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vhardware_id\x18\x02 \x01(\tR\n" +
	"hardwareId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12!\n" +
	"\fprocess_name\x18\x05 \x01(\tR\vprocessName\x12\x1d\n" +
	"\n" +
	"process_id\x18\x06 \x01(\x05R\tprocessId\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12*\n" +
	"\x11parent_process_id\x18\b \x01(\x05R\x0fparentProcessId\x12!\n" +
	"\fthreat_score\x18\t \x01(\x05R\vthreatScore\x12\x1d\n" +
	"\n" +
	"ai_verdict\x18\n" +
	" \x01(\tR\taiVerdict\"P\n" +
	"\tStreamAck\x12)\n" +
	"\x10events_processed\x18\x01 \x01(\x05R\x0feventsProcessed\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9c\x01\n" +
	"\rCommandResult\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vhardware_id\x18\x02 \x01(\tR\n" +
	"hardwareId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\"`\n" +
	"\rServerCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"q\n" +
	"\vScanRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12'\n" +
	"\x0fenabled_engines\x18\x03 \x03(\tR\x0eenabledEngines\"\xf8\x01\n" +
	"\fScanResponse\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1a\n" +
	"\binfected\x18\x02 \x01(\bR\binfected\x12!\n" +
	"\fthreat_level\x18\x03 \x01(\tR\vthreatLevel\x12.\n" +
	"\athreats\x18\x04 \x03(\v2\x14.aftersec.api.ThreatR\athreats\x12!\n" +
	"\fengines_used\x18\x05 \x03(\tR\venginesUsed\x12#\n" +
	"\rscan_duration\x18\x06 \x01(\tR\fscanDuration\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"r\n" +
	"\x06Threat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\"&\n" +
	"\x0eHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x0fHistoryResponse\x12\x1f\n" +
	"\vtotal_scans\x18\x01 \x01(\x05R\n" +
	"totalScans\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x120\n" +
	"\x05scans\x18\x03 \x03(\v2\x1a.aftersec.api.HistoryEntryR\x05scans\"\xf3\x01\n" +
	"\fHistoryEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\binfected\x18\x03 \x01(\bR\binfected\x12!\n" +
	"\fthreat_count\x18\x04 \x01(\x05R\vthreatCount\x12!\n" +
	"\fthreat_names\x18\x05 \x03(\tR\vthreatNames\x12!\n" +
	"\fengines_used\x18\x06 \x03(\tR\venginesUsed\x12#\n" +
	"\rscan_duration\x18\a \x01(\tR\fscanDuration\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x81\x01\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\x124\n" +
	"\aresults\x18\x03 \x03(\v2\x1a.aftersec.api.SearchResultR\aresults\"\xd5\x01\n" +
	"\fSearchResult\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_hash\x18\x03 \x01(\tR\bfileHash\x12\x1a\n" +
	"\binfected\x18\x04 \x01(\bR\binfected\x12.\n" +
	"\athreats\x18\x05 \x03(\v2\x14.aftersec.api.ThreatR\athreats\x12!\n" +
	"\fengines_used\x18\x06 \x03(\tR\venginesUsed2\xc2\x02\n" +
	"\x11EnterpriseService\x12C\n" +
	"\x06Enroll\x12\x1b.aftersec.api.EnrollRequest\x1a\x1c.aftersec.api.EnrollResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.aftersec.api.HeartbeatRequest\x1a\x1f.aftersec.api.HeartbeatResponse\x12D\n" +
	"\fStreamEvents\x12\x19.aftersec.api.ClientEvent\x1a\x17.aftersec.api.StreamAck(\x01\x12T\n" +
	"\x14ConnectCommandStream\x12\x1b.aftersec.api.CommandResult\x1a\x1b.aftersec.api.ServerCommand(\x010\x012\xef\x01\n" +
	"\x12MalwareScanService\x12A\n" +
	"\bScanFile\x12\x19.aftersec.api.ScanRequest\x1a\x1a.aftersec.api.ScanResponse\x12J\n" +
	"\vScanHistory\x12\x1c.aftersec.api.HistoryRequest\x1a\x1d.aftersec.api.HistoryResponse\x12J\n" +
	"\rSearchHistory\x12\x1b.aftersec.api.SearchRequest\x1a\x1c.aftersec.api.SearchResponseB\x1fZ\x1daftersec/pkg/api/grpc;grpcapib\x06proto3"

var (
	file_api_proto_aftersec_proto_rawDescOnce sync.Once
	file_api_proto_aftersec_proto_rawDescData []byte
)

func file_api_proto_aftersec_proto_rawDescGZIP() []byte {
	file_api_proto_aftersec_proto_rawDescOnce.Do(func() {
		file_api_proto_aftersec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_aftersec_proto_rawDesc), len(file_api_proto_aftersec_proto_rawDesc)))
	})
	return file_api_proto_aftersec_proto_rawDescData
}

var file_api_proto_aftersec_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_proto_aftersec_proto_goTypes = []any{
	(*EnrollRequest)(nil),     // 0: aftersec.api.EnrollRequest
	(*EnrollResponse)(nil),    // 1: aftersec.api.EnrollResponse
	(*HeartbeatRequest)(nil),  // 2: aftersec.api.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: aftersec.api.HeartbeatResponse
	(*ClientEvent)(nil),       // 4: aftersec.api.ClientEvent
	(*StreamAck)(nil),         // 5: aftersec.api.StreamAck
	(*CommandResult)(nil),     // 6: aftersec.api.CommandResult
	(*ServerCommand)(nil),     // 7: aftersec.api.ServerCommand
	(*ScanRequest)(nil),       // 8: aftersec.api.ScanRequest
	(*ScanResponse)(nil),      // 9: aftersec.api.ScanResponse
	(*Threat)(nil),            // 10: aftersec.api.Threat
	(*HistoryRequest)(nil),    // 11: aftersec.api.HistoryRequest
	(*HistoryResponse)(nil),   // 12: aftersec.api.HistoryResponse
	(*HistoryEntry)(nil),      // 13: aftersec.api.HistoryEntry
	(*SearchRequest)(nil),     // 14: aftersec.api.SearchRequest
	(*SearchResponse)(nil),    // 15: aftersec.api.SearchResponse
	(*SearchResult)(nil),      // 16: aftersec.api.SearchResult
}
var file_api_proto_aftersec_proto_depIdxs = []int32{
	10, // 0: aftersec.api.ScanResponse.threats:type_name -> aftersec.api.Threat
	13, // 1: aftersec.api.HistoryResponse.scans:type_name -> aftersec.api.HistoryEntry
	16, // 2: aftersec.api.SearchResponse.results:type_name -> aftersec.api.SearchResult
	10, // 3: aftersec.api.SearchResult.threats:type_name -> aftersec.api.Threat
	0,  // 4: aftersec.api.EnterpriseService.Enroll:input_type -> aftersec.api.EnrollRequest
	2,  // 5: aftersec.api.EnterpriseService.Heartbeat:input_type -> aftersec.api.HeartbeatRequest
	4,  // 6: aftersec.api.EnterpriseService.StreamEvents:input_type -> aftersec.api.ClientEvent
	6,  // 7: aftersec.api.EnterpriseService.ConnectCommandStream:input_type -> aftersec.api.CommandResult
	8,  // 8: aftersec.api.MalwareScanService.ScanFile:input_type -> aftersec.api.ScanRequest
	11, // 9: aftersec.api.MalwareScanService.ScanHistory:input_type -> aftersec.api.HistoryRequest
	14, // 10: aftersec.api.MalwareScanService.SearchHistory:input_type -> aftersec.api.SearchRequest
	1,  // 11: aftersec.api.EnterpriseService.Enroll:output_type -> aftersec.api.EnrollResponse
	3,  // 12: aftersec.api.EnterpriseService.Heartbeat:output_type -> aftersec.api.HeartbeatResponse
	5,  // 13: aftersec.api.EnterpriseService.StreamEvents:output_type -> aftersec.api.StreamAck
	7,  // 14: aftersec.api.EnterpriseService.ConnectCommandStream:output_type -> aftersec.api.ServerCommand
	9,  // 15: aftersec.api.MalwareScanService.ScanFile:output_type -> aftersec.api.ScanResponse
	12, // 16: aftersec.api.MalwareScanService.ScanHistory:output_type -> aftersec.api.HistoryResponse
	15, // 17: aftersec.api.MalwareScanService.SearchHistory:output_type -> aftersec.api.SearchResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_aftersec_proto_init() }
func file_api_proto_aftersec_proto_init() {
	if File_api_proto_aftersec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_aftersec_proto_rawDesc), len(file_api_proto_aftersec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_aftersec_proto_goTypes,
		DependencyIndexes: file_api_proto_aftersec_proto_depIdxs,
		MessageInfos:      file_api_proto_aftersec_proto_msgTypes,
	}.Build()
	File_api_proto_aftersec_proto = out.File
	file_api_proto_aftersec_proto_goTypes = nil
	file_api_proto_aftersec_proto_depIdxs = nil
}
